const ADD_SKILL = "ADD_SKILL";
const DELETE_SKILL = "DELETE_SKILL";
const GET_RECOMM = "GET_RECOMM"
const CHOOSE_RECOMM = "CHOOSE_RECOMM"

export { ADD_SKILL, DELETE_SKILL, GET_RECOMM, CHOOSE_RECOMM};
